apiVersion: apps/v1
kind: Deployment
metadata:
  name: idisi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idisi
  template:
    metadata:
      labels:
        app: idisi
    spec:
      containers:
      - name: idisi
        image: registry.gitlab.com/irdoo/api
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: idisi
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: idisi