apiVersion: apps/v1
kind: Deployment
metadata:
  name: idisi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idisi
  template:
    metadata:
      labels:
        app: idisi
    spec:
      containers:
      - name: idisi
        image: registry.gitlab.com/irdoo/api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: idisi
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    app: idisi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idisi
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  rules:
    - host: ec2-3-0-18-62.ap-southeast-1.compute.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: idisi
                port:
                  number: 3000