apiVersion: apps/v1
kind: Deployment
metadata:
  name: idisi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: idisi
  template:
    metadata:
      labels:
        app: idisi
    spec:
      containers:
      - name: idisi
        image: registry.gitlab.com/irdoo/api
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: idisi
spec:
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  selector:
    app: idisi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idisi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: idisi
                port:
                  number: 80